Issue 17 enchace xml writer
prowide/prowide-iso20022 pull request #20
Opened 2021-04-26 14:48 UTC by alexandergorokhov

2021-04-26 18:14 UTC, zubri requested changes

2021-04-26 18:14 UTC, zubri commented on iso20022-core/src/main/java/com/prowidesoftware/swift/model/mx/XmlEventWriter.java
> +								ee.toString().equals(this.previousEndElement.toString())) {
En vez de usar los toString que es error prone, tendrías que levantar el local name de ambos elementos y comparar eso. Como hacemos para el current.

2021-04-26 18:14 UTC, zubri commented on iso20022-core/src/main/java/com/prowidesoftware/swift/model/mx/XmlEventWriter.java
> +						if (!localPart.equals(this.currentElement)) {
No iria en un else if esta parte? Puede ser que entre en los dos IF y que genere doble ident?

2021-04-26 18:19 UTC, zubri commented on iso20022-core/src/test/java/com/prowidesoftware/swift/model/mx/MxWriteTest.java
> +		final String xml = Lib.readResource("pacs.002-CDATA.xml");
Este sample es particular, tiene un montón de CDATA para unas pruebas puntuales. Create un Mx con el API Java en vez de con un XML, total solo necesitas un elemento con currency para probar el issue.

2021-04-26 18:19 UTC, zubri commented on iso20022-core/src/test/java/com/prowidesoftware/swift/model/mx/MxWriteTest.java
> +		System.out.println(xml);
Essos system out depsues dejaselos de nuevo comentados, pq al correr Jenkins ensucian todo el log

2021-04-27 00:48 UTC, alexandergorokhov commented on iso20022-core/src/test/java/com/prowidesoftware/swift/model/mx/MxWriteTest.java
> +		System.out.println(xml);
Si. No deberia ser parte del PR.

2021-04-27 00:48 UTC, alexandergorokhov commented on iso20022-core/src/test/java/com/prowidesoftware/swift/model/mx/MxWriteTest.java
> +		final String xml = Lib.readResource("pacs.002-CDATA.xml");
Idem. No deberia ser parte del PR.

2021-04-27 01:01 UTC, closed without merging