CU-85ztm247h_PW-1462--PMH-Bottomline-GTX-extension-test-case-fails-to…
prowide/prowide-iso20022 pull request #97
Opened 2023-08-08 18:19 UTC by ptorres-prowide

…-parse-xsys002

2023-08-22 22:17 UTC, zubri requested changes

2023-08-22 22:17 UTC, zubri commented on iso20022-core/src/main/java/com/prowidesoftware/swift/model/mx/MxReadImpl.java
> +    private static String getDocumentXml(String xml, MxReadParams params) {
Este metodo no se usa por lo que veo. Es el intento por lo de Any? En general hay que evitar usar DOM, es muy lento, por eso usamos Sax

2023-08-22 22:17 UTC, zubri commented on iso20022-core/src/test/resources/sample_hvcs_xsys.002_pacs.008_namespaces.xml
> +                    <SwInt:RequestRef>201207190001100005007HV0</SwInt:RequestRef>
Ademas de BIC hay que cambiar las referencias y los montos con cosas obviamente dummy como 99999.99

2023-08-23 01:09 UTC, ptorres-prowide commented on iso20022-core/src/main/java/com/prowidesoftware/swift/model/mx/MxReadImpl.java
> +    private static String getDocumentXml(String xml, MxReadParams params) {
La llamada a este método está comentada. Habíamos quedado en que lo subía así y vos revisabas si no encontrabas una solución mejor. Este branch fue una 1era idea que no te convencía.

2024-10-31 19:51 UTC, closed without merging